[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/api/query/citaciones"
  to = "/.netlify/functions/citaciones-real"
  status = 200

[[redirects]]
  from = "/api/query/sesiones"
  to = "/.netlify/functions/sesiones-real"
  status = 200

[[redirects]]
  from = "/api/query/calendario"
  to = "/.netlify/functions/calendario-real"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200 